; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.25019.0 

	TITLE	C:\Users\57626\documents\visual studio 2017\Projects\asmtry\exp\getrec.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

_DATA	SEGMENT
$SG6223	DB	'%s%d%d%d', 00H
_DATA	ENDS
PUBLIC	___local_stdio_scanf_options
PUBLIC	__vfscanf_l
PUBLIC	_scanf
PUBLIC	_getrec
EXTRN	__imp____acrt_iob_func:PROC
EXTRN	__imp____stdio_common_vfscanf:PROC
EXTRN	_info:BYTE
_DATA	SEGMENT
COMM	?_OptionsStorage@?1??__local_stdio_scanf_options@@9@9:QWORD							; `__local_stdio_scanf_options'::`2'::_OptionsStorage
_DATA	ENDS
; Function compile flags: /Odtp
; File c:\users\57626\documents\visual studio 2017\projects\asmtry\exp\getrec.c
;	COMDAT _getrec
_TEXT	SEGMENT
_c$1 = -16						; size = 4
_b$2 = -12						; size = 4
_a$3 = -8						; size = 4
_i$4 = -4						; size = 4
_getrec	PROC						; COMDAT

; 2    : void getrec() {

	push	ebp
	mov	ebp, esp
	sub	esp, 16					; 00000010H

; 3    : 	for (int i = 0; i < N; ++i) {

	mov	DWORD PTR _i$4[ebp], 0
	jmp	SHORT $LN4@getrec
$LN2@getrec:
	mov	eax, DWORD PTR _i$4[ebp]
	add	eax, 1
	mov	DWORD PTR _i$4[ebp], eax
$LN4@getrec:
	cmp	DWORD PTR _i$4[ebp], 2
	jge	SHORT $LN1@getrec

; 4    : 		int a, b, c;
; 5    : 		scanf("%s%d%d%d", info[i].name, &a, &b, &c);

	lea	ecx, DWORD PTR _c$1[ebp]
	push	ecx
	lea	edx, DWORD PTR _b$2[ebp]
	push	edx
	lea	eax, DWORD PTR _a$3[ebp]
	push	eax
	mov	ecx, DWORD PTR _i$4[ebp]
	shl	ecx, 4
	add	ecx, OFFSET _info
	push	ecx
	push	OFFSET $SG6223
	call	_scanf
	add	esp, 20					; 00000014H

; 6    : 		info[i].grade[0] = (char)a;

	mov	edx, DWORD PTR _i$4[ebp]
	shl	edx, 4
	mov	eax, 1
	imul	ecx, eax, 0
	mov	al, BYTE PTR _a$3[ebp]
	mov	BYTE PTR _info[edx+ecx+10], al

; 7    : 		info[i].grade[1] = (char)b;

	mov	ecx, DWORD PTR _i$4[ebp]
	shl	ecx, 4
	mov	edx, 1
	shl	edx, 0
	mov	al, BYTE PTR _b$2[ebp]
	mov	BYTE PTR _info[ecx+edx+10], al

; 8    : 		info[i].grade[2] = (char)c;

	mov	ecx, DWORD PTR _i$4[ebp]
	shl	ecx, 4
	mov	edx, 1
	shl	edx, 1
	mov	al, BYTE PTR _c$1[ebp]
	mov	BYTE PTR _info[ecx+edx+10], al

; 9    : 	}	

	jmp	SHORT $LN2@getrec
$LN1@getrec:

; 10   : }

	mov	esp, ebp
	pop	ebp
	ret	0
_getrec	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\program files (x86)\windows kits\10\include\10.0.14393.0\ucrt\stdio.h
;	COMDAT _scanf
_TEXT	SEGMENT
__Result$ = -8						; size = 4
__ArgList$ = -4						; size = 4
__Format$ = 8						; size = 4
_scanf	PROC						; COMDAT

; 1275 :     {

	push	ebp
	mov	ebp, esp
	sub	esp, 8

; 1276 :         int _Result;
; 1277 :         va_list _ArgList;
; 1278 :         __crt_va_start(_ArgList, _Format);

	lea	eax, DWORD PTR __Format$[ebp+4]
	mov	DWORD PTR __ArgList$[ebp], eax

; 1279 :         _Result = _vfscanf_l(stdin, _Format, NULL, _ArgList);

	mov	ecx, DWORD PTR __ArgList$[ebp]
	push	ecx
	push	0
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	push	0
	call	DWORD PTR __imp____acrt_iob_func
	add	esp, 4
	push	eax
	call	__vfscanf_l
	add	esp, 16					; 00000010H
	mov	DWORD PTR __Result$[ebp], eax

; 1280 :         __crt_va_end(_ArgList);

	mov	DWORD PTR __ArgList$[ebp], 0

; 1281 :         return _Result;

	mov	eax, DWORD PTR __Result$[ebp]

; 1282 :     }

	mov	esp, ebp
	pop	ebp
	ret	0
_scanf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\program files (x86)\windows kits\10\include\10.0.14393.0\ucrt\stdio.h
;	COMDAT __vfscanf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfscanf_l PROC					; COMDAT

; 1057 :     {

	push	ebp
	mov	ebp, esp

; 1058 :         return __stdio_common_vfscanf(

	mov	eax, DWORD PTR __ArgList$[ebp]
	push	eax
	mov	ecx, DWORD PTR __Locale$[ebp]
	push	ecx
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	mov	eax, DWORD PTR __Stream$[ebp]
	push	eax
	call	___local_stdio_scanf_options
	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	mov	edx, DWORD PTR [eax]
	push	edx
	call	DWORD PTR __imp____stdio_common_vfscanf
	add	esp, 24					; 00000018H

; 1059 :             _CRT_INTERNAL_LOCAL_SCANF_OPTIONS,
; 1060 :             _Stream, _Format, _Locale, _ArgList);
; 1061 :     }

	pop	ebp
	ret	0
__vfscanf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\program files (x86)\windows kits\10\include\10.0.14393.0\ucrt\corecrt_stdio_config.h
;	COMDAT ___local_stdio_scanf_options
_TEXT	SEGMENT
___local_stdio_scanf_options PROC			; COMDAT

; 94   :     {

	push	ebp
	mov	ebp, esp

; 95   :         static unsigned __int64 _OptionsStorage;
; 96   :         return &_OptionsStorage;

	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_scanf_options@@9@9 ; `__local_stdio_scanf_options'::`2'::_OptionsStorage

; 97   :     }

	pop	ebp
	ret	0
___local_stdio_scanf_options ENDP
_TEXT	ENDS
E